# Generated by Django 2.2.3 on 2019-07-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='api.PlaylistMembership', to='api.Track'),
        ),
        migrations.AlterField(
            model_name='playlistmembership',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Playlist'),
        ),
        migrations.AlterField(
            model_name='playlistmembership',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists',
                                    to='api.Track'),
        ),
    ]
