# Generated by Django 2.2.3 on 2019-07-18 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20190718_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='track',
            field=models.ForeignKey(default={'id': 3}, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='receivers', to='api.Track'),
        ),
    ]
