# Generated by Django 2.2.3 on 2019-07-18 13:17

import django.db.models.deletion
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20190718_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='track',
            field=models.ForeignKey(default=api.models.Track.objects.first(),
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='receivers',
                                    to='api.Track'),
        ),
    ]
